
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/qhaladb
    username: postgres
    password: qwerty
  application:
    name: orders-service


server:
  port: 8089
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}